# Generated by Django 2.2 on 2019-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_laborados', models.CharField(max_length=3)),
                ('sueldo', models.CharField(max_length=20)),
                ('auxlio_transporte', models.CharField(max_length=20)),
                ('total_devengado', models.CharField(max_length=20)),
                ('salud', models.CharField(max_length=20)),
                ('pension', models.CharField(max_length=20)),
                ('fsp', models.CharField(max_length=20)),
                ('total_deducido', models.CharField(max_length=20)),
                ('neto_pagar', models.CharField(max_length=20)),
                ('empleado_id', models.CharField(max_length=20)),
            ],
        ),
    ]
