# Generated by Django 2.2 on 2019-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.CharField(max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
